### ISSUE TITLE
Panic querying files larger than 10GB

### ISSUE THREAD

**Issue by swordbeta** [kshvmdn/fsql#13]
Query:

`select * from / where size > 10GB`

Panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x4c56d1]

goroutine 1 [running]:
main.compare(0xc420012408, 0x4, 0x12, 0xc420012440, 0x2, 0x0, 0x0, 0x0, 0x0)
	/home/michael/Projects/go/src/github.com/kshvmdn/fsql/main.go:55 +0x2e1
github.com/kshvmdn/fsql/query.(*ConditionNode).Evaluate(0xc42000c600, 0x0, 0x0, 0x4e0b20, 0x505c38, 0x7fae1cd0b400)
	/home/michael/Projects/go/src/github.com/kshvmdn/fsql/query/query.go:113 +0x80
main.main.func1(0xc4203db550, 0xf, 0x0, 0x0, 0x56d620, 0xc4203d5ce0, 0x0, 0x0)
	/home/michael/Projects/go/src/github.com/kshvmdn/fsql/main.go:120 +0x162
path/filepath.walk(0xc4203db4b0, 0xd, 0x56e720, 0xc420251520, 0xc42000c620, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc4203db1f4, 0xa, 0x56e720, 0xc4202505b0, 0xc42000c620, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0xc420013880, 0x5, 0x56e720, 0xc42042dad0, 0xc42000c620, 0x0, 0x0)
	/usr/lib/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0xc4200123a8, 0x1, 0x56e720, 0xc420078680, 0xc42000c620, 0x0, 0x20)
	/usr/lib/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc4200123a8, 0x1, 0xc42000c620, 0x1, 0xc420096000)
	/usr/lib/go/src/path/filepath/path.go:398 +0x14c
main.main()
	/home/michael/Projects/go/src/github.com/kshvmdn/fsql/main.go:144 +0x3bb
```

It outputted two files before crashing. Go version 1.8.1 linux/amd64, do you need more information?

**Comment by kshvmdn** [comment]
Thanks for reporting this.

The panic is originating from [this line](https://github.com/kshvmdn/fsql/blob/master/main.go#L55), meaning one of `comparator` or `file` are `nil`. It can't be `comparator`, since it _did_ output other files before crashing. Perhaps this is happening because of insufficient permissions on the file it was reading, which should be reported as an error [filepath.Walk](https://github.com/kshvmdn/fsql/blob/master/main.go#L120).

I'll play around with it a little bit more.

**Comment by swordbeta** [comment]
@kshvmdn The latest commit indeed fixes this!

I did some debugg and It's a permission issue, even though I did try using root. It was some kind of socket that no one on my system has permission to:

```
➜ ls -la /proc/1486/task/1514/fd/227
lrwx------ 1 michael michael 64 May 16 16:36 /proc/1486/task/1514/fd/227 -> socket:[1853933]
```

**Comment by kshvmdn** [comment]
Awesome! 

Kind of odd that running it as root didn't fix it. Either way, glad it's working now!
